server:
  port: 80

spring:
  mvc:
    view:
      suffix: .html
      prefix: /
  profiles:
    active: dev

  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
