server:
  port: 80

spring:
  mvc:
    view:
      suffix: .html
      prefix: /
  profiles:
    active: prod

  jackson:
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
